[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
index-strategy = "unsafe-best-match"
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
]
override-dependencies = [
    "nvidia-nccl-cu12; sys_platform == 'linux'",
]
default-groups = ["web"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "llama-cpp-metal"
url = "https://abetlen.github.io/llama-cpp-python/whl/metal/"
explicit = true

[[tool.uv.index]]
name = "llama-cpp-win-cpu"
url = "https://pnnbao97.github.io/llama-cpp-python-v0.3.16/cpu/"
explicit = true

[project]
name = "vieneu"
version = "1.2.9"
description = "Advanced on-device Vietnamese TTS with instant voice cloning"
readme = "README.md"
authors = [
    { name = "Phạm Nguyễn Ngọc Bảo", email = "pnnbao@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "sea-g2p==0.6.8",
    "neucodec>=0.0.4",
    "librosa>=0.11.0",
    "onnxruntime>=1.23.2",
    "datasets>=3.2.0",
    "torch>=2.7.1,<2.9",
    "torchvision>=0.22.1,<0.25",
    "torchaudio>=2.7.1,<2.9",
    "perth>=0.2.0",
    "llama-cpp-python==0.3.16",
    "requests",
]

[project.urls]
"Homepage" = "https://github.com/pnnbao97/VieNeu-TTS"
"Bug Tracker" = "https://github.com/pnnbao97/VieNeu-TTS/issues"
"Documentation" = "https://github.com/pnnbao97/VieNeu-TTS/blob/main/README.md"
"Source Code" = "https://github.com/pnnbao97/VieNeu-TTS"
"Changelog" = "https://github.com/pnnbao97/VieNeu-TTS/releases"

[project.optional-dependencies]
gpu = [
    "lmdeploy; sys_platform != 'darwin'",
    "triton-windows; sys_platform == 'win32'",
    "triton; sys_platform == 'linux'",
    "transformers; sys_platform == 'darwin'",
    "accelerate; sys_platform == 'darwin'",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

web = [
    "lmdeploy; sys_platform != 'darwin'",
    "triton-windows; sys_platform == 'win32'",
    "triton; sys_platform == 'linux'",
    "transformers; sys_platform == 'darwin'",
    "accelerate; sys_platform == 'darwin'",
    "gradio>=5.49.1",
    "trafilatura>=2.0.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[project.scripts]
vieneu-web = "apps.gradio_main:main"
vieneu-stream = "apps.web_stream:main"

[tool.setuptools]
package-dir = {"" = "src", "apps" = "apps", "examples" = "examples"}

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["vieneu*", "vieneu_utils*", "apps*", "examples*"]

[tool.setuptools.package-data]
vieneu = ["assets/samples/*"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" }
]

torchaudio = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" }
]

torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" }
]

llama-cpp-python = [
    { index = "llama-cpp-win-cpu", marker = "sys_platform == 'win32'" },
    { index = "llama-cpp-metal", marker = "sys_platform == 'darwin'" },
    { index = "pypi", marker = "sys_platform != 'win32' and sys_platform != 'darwin'" }
]
